{
  "vault_path": "{{VAULT_PATH}}",
  "timezone": "{{TIMEZONE}}",
  "run_hours": {{RUN_HOURS_JSON}},
  "source_retention_days": 7,
  "stable_file_minutes": 10,
  "manual_only_paths": ["20 工作/29 SOP"],
  "provider_order": {{PROVIDER_ORDER_JSON}},
  "codex_binary": "/Applications/ChatGPT.app/Contents/Resources/codex",
  "codex_min_version": "0.144.5",
  "codex_model": "gpt-5.6-luna",
  "codex_reasoning_effort": "medium",
  "codex_timeout_seconds": 180,
  "codex_batch_max_items": 10,
  "codex_batch_max_chars": 80000,
  "deepseek_model": "deepseek-v4-flash",
  "deepseek_timeout_seconds": 120,
  "deepseek_thinking": false,
  "keychain_service": "{{KEYCHAIN_SERVICE}}",
  "api_providers": {{API_PROVIDERS_JSON}},
  "expected_community_plugins": ["knowledge-vault-auto-properties"],
  "strict_local_audit": false,
  "whisper_binary": "{{HOMEBREW_PREFIX}}/bin/whisper-cli",
  "whisper_model": "{{HOME}}/.local/share/knowledge-vault/models/ggml-small.bin"
}
